package io.relay.app

import io.relay.app.core.UpdateDownload
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Rule
import org.junit.Test
import org.junit.rules.TemporaryFolder
import java.io.File

/**
 * The update path, which ends in handing a file to the package installer.
 *
 * These are all about the refusals. Every one of them is a way Relay could end
 * up offering someone an APK that is not the one the release published.
 */
class UpdateDownloadTest {

    @get:Rule
    val folder = TemporaryFolder()

    private fun apk(name: String, contents: String): File =
        folder.newFile(name).apply { writeText(contents) }

    private fun listing(vararg entries: Pair<File, Boolean>): String =
        entries.joinToString("\n") { (file, correct) ->
            val hash = if (correct) {
                UpdateDownload.sha256(file.inputStream())
            } else {
                "0".repeat(64)
            }
            "$hash  ${file.name}"
        }

    @Test
    fun `accepts an apk whose hash is the one the release published`() {
        val file = apk("Relay-android-arm64-v8a.apk", "pretend apk")

        val result = UpdateDownload.verify(file, listing(file to true))

        assertTrue(result is UpdateDownload.Result.Ready)
        assertTrue("a verified apk must survive", file.exists())
    }

    @Test
    fun `rejects and deletes an apk whose hash does not match`() {
        val file = apk("Relay-android-arm64-v8a.apk", "not what was published")

        val result = UpdateDownload.verify(file, listing(file to false))

        assertEquals(UpdateDownload.Result.ChecksumMismatch, result)
        // It must not be left in the cache where it could be opened later.
        assertFalse("a rejected apk must not stay on disk", file.exists())
    }

    @Test
    fun `refuses when the listing does not mention this file at all`() {
        val file = apk("Relay-android-arm64-v8a.apk", "pretend apk")
        val other = apk("Relay-android-universal.apk", "a different build")

        val result = UpdateDownload.verify(file, listing(other to true))

        assertEquals(UpdateDownload.Result.Unverifiable, result)
        assertFalse(file.exists())
    }

    @Test
    fun `reads every shape of checksum line the tools produce`() {
        val hash = "a".repeat(64)
        val name = "Relay-android-arm64-v8a.apk"
        listOf("$hash  $name", "$hash *$name", "$hash  ./$name").forEach { line ->
            assertEquals(line, hash, UpdateDownload.hashFor(line, name))
        }
    }

    @Test
    fun `ignores comments and lines that are not a hash and a name`() {
        val listing = "# generated by the release workflow\n\nnope  Relay-android-universal.apk\n"
        assertNull(UpdateDownload.hashFor(listing, "Relay-android-universal.apk"))
    }

    @Test
    fun `prefers the apk built for this device's abi`() {
        val names = listOf(
            "Relay-android-arm64-v8a.apk",
            "Relay-android-universal.apk",
            "Relay-android.aab",
        )

        assertEquals(
            "Relay-android-arm64-v8a.apk",
            UpdateDownload.assetFor(names, listOf("arm64-v8a", "armeabi-v7a")),
        )
    }

    @Test
    fun `falls back to the universal apk when no abi matches`() {
        val names = listOf("Relay-android-arm64-v8a.apk", "Relay-android-universal.apk")

        assertEquals(
            "Relay-android-universal.apk",
            UpdateDownload.assetFor(names, listOf("riscv64")),
        )
    }

    @Test
    fun `never offers the aab, which cannot be installed`() {
        val names = listOf("Relay-android.aab", "SHA256SUMS.txt")

        assertNull(UpdateDownload.assetFor(names, listOf("arm64-v8a")))
    }
}
