using System.Globalization;

namespace Relay.App;

/// <summary>
/// Localized strings held entirely in code (English + Persian). This app is
/// unpackaged, where the MRT <c>ResourceLoader</c> can throw a stowed COM
/// exception at startup that escapes managed try/catch; keeping strings in
/// code removes that failure mode entirely. Selection follows the OS UI
/// language; anything missing falls back to English, then to the key itself.
///
/// This is the only string store, and it has to stay that way. A pair of .resw
/// files sat alongside it for several releases, read by nothing: new keys were
/// added there, this file never got them, and the fallback quietly showed the
/// user identifiers — "CodeNoDevice" where a sentence should have been. If a
/// string is not here, it does not exist. <c>StringsCoverageTests</c> holds
/// that line.
/// </summary>
public static class Strings
{
    private static readonly bool IsPersian =
        CultureInfo.CurrentUICulture.TwoLetterISOLanguageName.Equals("fa", StringComparison.OrdinalIgnoreCase);

    public static string Get(string key)
    {
        if (IsPersian && Fa.TryGetValue(key, out var fa)) return fa;
        return En.TryGetValue(key, out var en) ? en : key;
    }

    private static readonly Dictionary<string, string> En = new()
    {
        ["AppName"] = "Relay",
        ["Tagline"] = "Share your connection. Instantly.",
        ["StatusIdle"] = "Not connected",
        ["StatusConnecting"] = "Connecting…",
        ["StatusConnected"] = "Connected",
        ["NotifyConnectedTitle"] = "Relay is connected",
        ["NotifyConnectedBody"] = "This PC is now using your phone's connection.",
        ["StatDown"] = "Download",
        ["StatUp"] = "Upload",
        ["StatLatency"] = "Tunnel latency",
        ["StatLatencyUnknown"] = "Tunnel latency —",
        ["StatConnectedFor"] = "Connected for",
        ["ScanQr"] = "Scan QR",
        ["EnterCode"] = "Enter the 2-digit code",
        ["ScanHint"] = "Point the camera at the QR on your phone",
        ["CodeHint"] = "The two digits shown on your phone",
        ["CodeHintLong"] = "The 8-character code your phone is showing",
        ["Connect"] = "Connect",
        ["Cancel"] = "Cancel",
        ["Disconnect"] = "Disconnect",
        ["Dismiss"] = "Dismiss",
        ["Reconnecting"] = "Reconnecting…",
        ["TrayOpen"] = "Open Relay",
        ["TrayExit"] = "Exit",
        ["ConnectedVia"] = "Connected via {0}",
        ["Advanced"] = "Advanced",
        ["AdvancedVersion"] = "Version",
        ["WindowMinimise"] = "Minimise",
        ["WindowClose"] = "Close to the tray",
        ["WindowCloseHint"] = "Relay keeps running. Use Exit on the tray icon to quit.",
        ["AdvancedStartup"] = "Start with Windows",
        ["AdvancedLeakBlock"] = "Block traffic around the tunnel",
        ["AdvancedLeakBlockOn"] = "On",
        ["AdvancedLeakBlockOff"] = "Off",
        ["AdvancedLeakBlockHint"] = "Stops DNS and IPv6 escaping past the tunnel. Turning it off also lets Relay follow the phone to a new address.",
        ["AdvancedStartupOn"] = "On",
        ["AdvancedStartupOff"] = "Off",
        ["AdvancedStartupFailed"] = "Windows would not save that",
        ["AdvancedAddress"] = "Hotspot address",
        ["AdvancedLogs"] = "Activity log (stays on this PC)",
        ["AdvancedLogsClear"] = "Clear",
        // Copies the diagnostic report and opens a pre-filled issue. Named for
        // both halves, because the clipboard step is the surprising one.
        ["AdvancedLogsShare"] = "Copy & report",
        ["AdvancedLogsEmpty"] = "No activity yet",
        ["IdleHeadline"] = "Ready to connect",
        ["IdleBody"] = "Open Relay on your phone and tap Start Sharing. Then scan its QR, or type the two digits it shows.",
        ["ScanAiming"] = "Hold the QR inside the frame",
        ["CodeReady"] = "Looks good — connecting…",
        ["CodeHintShort"] = "One more digit",
        ["CodeDigitsOnly"] = "Two digits — the big number on the phone's screen",
        ["CodeNoLeadingZero"] = "Codes never start with a zero — check the first digit",
        ["CodeLooking"] = "Looking for that phone…",
        ["CodeFoundNamed"] = "Found {0} — connecting…",
        ["CodeAmbiguous"] = "Two phones are showing that code ({0}). Stop sharing on the one you don't want.",
        ["CodeNearby"] = "Sharing right now",
        ["IdleNearby"] = "Sharing right now — click one to connect",
        ["CodeUseLong"] = "My phone shows a longer code",
        ["CodeUseShort"] = "My phone shows two digits",
        ["CodeIncomplete"] = "{0} more characters",
        ["CodeBadChars"] = "Only the letters and digits shown on the phone",
        ["CodeChecksum"] = "That code isn't valid. Check it against the phone.",
        ["BusyConnecting"] = "Setting up the connection",
        ["BusyPairing"] = "Check your phone",
        ["BusyPairingDetail"] = "Your phone is asking whether to let this computer in. Tap Allow.",
        ["BusyDetail"] = "Checking the network and applying your proxy settings",
        ["ErrTitleNoPhone"] = "Can't reach your phone",
        ["ErrTitleNetwork"] = "Different networks",
        ["ErrTitleCode"] = "That code didn't work",
        ["ErrTitleCamera"] = "No camera available",
        ["ErrTitleBlocked"] = "Connection blocked",
        ["ErrTitleProxy"] = "Windows refused the change",
        ["ErrTitleRollback"] = "Proxy not fully restored",
        ["ErrTitleLost"] = "Connection lost",
        ["TryAgain"] = "Try Again",
        ["EnterCodeInstead"] = "Enter Code Instead",
        ["ErrQrInvalid"] = "That's not a Relay code. Show the QR from the Relay app on your phone and try again.",
        ["ErrQrNewer"] = "This code was made by a newer version of Relay — please update this app.",
        ["ErrCodeInvalid"] = "That code doesn't look right. Type the two digits shown on the phone.",
        ["ErrCodeNotFound"] = "No phone on this network is showing that code. Check that Relay is still sharing on the phone, and that this PC is on the phone's hotspot or the same Wi-Fi.",
        ["ErrCodeAmbiguous"] = "More than one phone is showing that code. Stop sharing on the one you don't want, then try again.",
        ["ErrFullModeNeedsQr"] = "That phone can't hand over a connection by code — something else on it is using the port Relay needs. Scan its QR code instead.",
        ["ErrHostUnreachable"] = "Can't reach your phone. Make sure this PC is on the same Wi-Fi as the phone (or the phone's hotspot), then try again.",
        ["ErrWrongNetwork"] = "This PC isn't on the same network as the phone. Join the same Wi-Fi (or the phone's hotspot), then try again.",
        ["ErrConnectionLost"] = "The phone became unreachable. Re-check the hotspot and connect again.",
        ["ErrFirewall"] = "The connection was blocked. Allow Relay through Windows Firewall (or your security software), then try again.",
        ["ErrProxyApply"] = "Windows refused the proxy change. Close other proxy/VPN managers and try again.",
        ["ErrRollback"] = "Relay couldn't fully restore your proxy settings. Disconnect again to retry.",
        ["ErrTitleElevation"] = "Full Mode needs permission",
        ["ErrTitleTunnel"] = "The tunnel didn't start",
        ["ErrWgElevationDeclined"] = "Relay has to create a network adapter, which Windows only allows with your permission. Choose Yes on the prompt to connect.",
        ["ErrWgStartFailed"] = "Relay couldn't bring the tunnel up. Close any other VPN that is running, then try again.",
        ["ErrTitleElevationBlocked"] = "Windows won't allow this here",
        ["ErrWgElevationUnavailable"] = "Windows refused to give Relay's tunnel administrator rights from the folder it's installed in, so it never asked you. This usually means that folder is redirected to another drive. Reinstalling Relay somewhere that isn't redirected fixes it.",
        ["ErrWgNoHandshake"] = "The tunnel came up but the phone never answered. Either its code changed — they change every time sharing restarts — or a VPN on the phone is swallowing Relay's replies, which the phone will say on its own screen.",
        ["ErrTitlePairing"] = "The phone didn't accept",
        ["ErrPairingDenied"] = "The phone declined this computer, or nobody answered the prompt. Tap Allow on the phone, then enter the code again.",
        ["ErrPairingVersion"] = "This phone is running an older version of Relay that can't pair by code. Update Relay on the phone, or scan its QR instead.",
        ["ErrWgStopFailed"] = "The tunnel process wouldn't stop. Restart Relay; the adapter and its routes are removed when it exits.",
        ["ErrCameraDenied"] = "Relay can't use the camera — it may be missing, in use by another app, or blocked. Allow camera access in Windows Settings > Privacy, or enter the code manually.",
    };

    private static readonly Dictionary<string, string> Fa = new()
    {
        ["AppName"] = "رله",
        ["Tagline"] = "اتصالت را به‌اشتراک بگذار. در یک لحظه.",
        ["StatusIdle"] = "متصل نیست",
        ["StatusConnecting"] = "در حال اتصال…",
        ["StatusConnected"] = "متصل شد",
        ["NotifyConnectedTitle"] = "رله متصل شد",
        ["NotifyConnectedBody"] = "این کامپیوتر حالا از اینترنت گوشی شما استفاده می‌کند.",
        ["StatDown"] = "دریافت",
        ["StatUp"] = "ارسال",
        ["StatLatency"] = "تأخیر تونل",
        ["StatLatencyUnknown"] = "تأخیر تونل —",
        ["StatConnectedFor"] = "مدت اتصال",
        ["ScanQr"] = "اسکن کد QR",
        ["EnterCode"] = "واردکردن کد ۲ رقمی",
        ["ScanHint"] = "دوربین را به‌سمت کد QR روی گوشی بگیرید",
        ["CodeHint"] = "همان دو رقمی که روی گوشی نوشته شده",
        ["CodeHintLong"] = "کد ۸ حرفی که گوشی نشان می‌دهد",
        ["Connect"] = "اتصال",
        ["Cancel"] = "انصراف",
        ["Disconnect"] = "قطع اتصال",
        ["Dismiss"] = "بستن",
        ["Reconnecting"] = "در حال اتصال مجدد…",
        ["TrayOpen"] = "بازکردن رله",
        ["TrayExit"] = "خروج",
        ["ConnectedVia"] = "متصل از طریق {0}",
        ["Advanced"] = "پیشرفته",
        ["AdvancedVersion"] = "نسخه",
        ["WindowMinimise"] = "کوچک‌کردن",
        ["WindowClose"] = "بستن به سینی",
        ["WindowCloseHint"] = "رله در حال اجرا می‌ماند. برای خروج، از «خروج» روی آیکون سینی استفاده کنید.",
        ["AdvancedStartup"] = "اجرا همراه ویندوز",
        ["AdvancedLeakBlock"] = "بستن مسیرهای دور تونل",
        ["AdvancedLeakBlockOn"] = "روشن",
        ["AdvancedLeakBlockOff"] = "خاموش",
        ["AdvancedLeakBlockHint"] = "جلوی خروج DNS و IPv6 از بیرون تونل را می‌گیرد. خاموش کردنش به رله اجازه می‌دهد گوشی را هنگام تغییر آدرس دنبال کند.",
        ["AdvancedStartupOn"] = "روشن",
        ["AdvancedStartupOff"] = "خاموش",
        ["AdvancedStartupFailed"] = "ویندوز این را ذخیره نکرد",
        ["AdvancedAddress"] = "نشانی هات‌اسپات",
        ["AdvancedLogs"] = "گزارش فعالیت (روی همین رایانه می‌ماند)",
        ["AdvancedLogsClear"] = "پاک‌کردن",
        ["AdvancedLogsShare"] = "کپی و گزارش",
        ["AdvancedLogsEmpty"] = "هنوز فعالیتی نیست",
        ["IdleHeadline"] = "آمادهٔ اتصال",
        ["IdleBody"] = "رله را روی گوشی باز کنید و «شروع اشتراک‌گذاری» را بزنید. بعد کد QR آن را اسکن کنید، یا همان دو رقمی را که نشان می‌دهد تایپ کنید.",
        ["ScanAiming"] = "کد QR را داخل کادر نگه دارید",
        ["CodeReady"] = "درست است — در حال اتصال…",
        ["CodeHintShort"] = "یک رقم دیگر",
        ["CodeDigitsOnly"] = "دو رقم — همان عدد درشت روی صفحهٔ گوشی",
        ["CodeNoLeadingZero"] = "کدها هیچ‌وقت با صفر شروع نمی‌شوند — رقم اول را دوباره ببینید",
        ["CodeLooking"] = "در حال گشتن به‌دنبال آن گوشی…",
        ["CodeFoundNamed"] = "{0} پیدا شد — در حال اتصال…",
        ["CodeAmbiguous"] = "دو گوشی همین کد را نشان می‌دهند ({0}). روی آن‌که نمی‌خواهید اشتراک‌گذاری را متوقف کنید.",
        ["CodeNearby"] = "همین حالا در حال اشتراک‌گذاری",
        ["IdleNearby"] = "همین حالا در حال اشتراک — برای اتصال یکی را بزنید",
        ["CodeUseLong"] = "گوشی من کد بلندتری نشان می‌دهد",
        ["CodeUseShort"] = "گوشی من دو رقم نشان می‌دهد",
        ["CodeIncomplete"] = "{0} حرف دیگر",
        ["CodeBadChars"] = "فقط حروف و ارقامی که روی گوشی نشان داده شده",
        ["CodeChecksum"] = "این کد معتبر نیست. آن را با گوشی بررسی کنید.",
        ["BusyConnecting"] = "در حال برقراری اتصال",
        ["BusyPairing"] = "گوشی‌تان را ببینید",
        ["BusyPairingDetail"] = "گوشی می‌پرسد که آیا این کامپیوتر اجازه دارد. «اجازه» را بزنید.",
        ["BusyDetail"] = "بررسی شبکه و اعمال تنظیمات پراکسی",
        ["ErrTitleNoPhone"] = "گوشی در دسترس نیست",
        ["ErrTitleNetwork"] = "شبکه‌ها یکی نیستند",
        ["ErrTitleCode"] = "این کد کار نکرد",
        ["ErrTitleCamera"] = "دوربینی در دسترس نیست",
        ["ErrTitleBlocked"] = "اتصال مسدود شد",
        ["ErrTitleProxy"] = "ویندوز تغییر را نپذیرفت",
        ["ErrTitleRollback"] = "پراکسی کاملاً بازنگشت",
        ["ErrTitleLost"] = "اتصال قطع شد",
        ["TryAgain"] = "تلاش دوباره",
        ["EnterCodeInstead"] = "به‌جایش کد را وارد کنید",
        ["ErrQrInvalid"] = "این کدِ رله نیست. کد QR را از برنامه رله روی گوشی نمایش دهید و دوباره تلاش کنید.",
        ["ErrQrNewer"] = "این کد با نسخه جدیدتری از رله ساخته شده — لطفاً این برنامه را به‌روزرسانی کنید.",
        ["ErrCodeInvalid"] = "این کد درست به‌نظر نمی‌رسد. همان دو رقمی را که روی گوشی نوشته شده وارد کنید.",
        ["ErrCodeNotFound"] = "هیچ گوشی‌ای روی این شبکه این کد را نشان نمی‌دهد. مطمئن شوید رله روی گوشی هنوز در حال اشتراک‌گذاری است و این رایانه به هات‌اسپات گوشی یا همان وای‌فای وصل است.",
        ["ErrCodeAmbiguous"] = "بیش از یک گوشی این کد را نشان می‌دهد. روی آن‌که نمی‌خواهید اشتراک‌گذاری را متوقف کنید و دوباره تلاش کنید.",
        ["ErrFullModeNeedsQr"] = "آن گوشی نمی‌تواند اتصال را با کد تحویل دهد — چیز دیگری روی گوشی پورتی را که رله لازم دارد اشغال کرده. به‌جایش کد QR آن را اسکن کنید.",
        ["ErrHostUnreachable"] = "گوشی در دسترس نیست. مطمئن شوید این رایانه روی همان وای‌فای گوشی (یا هات‌اسپات آن) است و دوباره تلاش کنید.",
        ["ErrWrongNetwork"] = "این رایانه روی شبکه‌ی گوشی نیست. به همان وای‌فای (یا هات‌اسپات گوشی) وصل شوید و دوباره تلاش کنید.",
        ["ErrConnectionLost"] = "گوشی از دسترس خارج شد. هات‌اسپات را بررسی کنید و دوباره وصل شوید.",
        ["ErrFirewall"] = "اتصال مسدود شد. به رله در فایروال ویندوز (یا نرم‌افزار امنیتی) اجازه دهید و دوباره تلاش کنید.",
        ["ErrProxyApply"] = "ویندوز تغییر پراکسی را نپذیرفت. مدیریت‌کننده‌های دیگر پراکسی/VPN را ببندید و دوباره تلاش کنید.",
        ["ErrRollback"] = "رله نتوانست تنظیمات پراکسی را کاملاً بازگرداند. برای تلاش دوباره، دوباره «قطع اتصال» را بزنید.",
        ["ErrTitleElevation"] = "حالت کامل به اجازه نیاز دارد",
        ["ErrTitleTunnel"] = "تونل بالا نیامد",
        ["ErrWgElevationDeclined"] = "رله باید یک آداپتور شبکه بسازد و ویندوز این کار را فقط با اجازهٔ شما انجام می‌دهد. برای اتصال، در پنجرهٔ ویندوز «بله» را بزنید.",
        ["ErrWgStartFailed"] = "رله نتوانست تونل را بالا بیاورد. اگر VPN دیگری روشن است ببندید و دوباره تلاش کنید.",
        ["ErrTitleElevationBlocked"] = "ویندوز اینجا اجازه نمی‌دهد",
        ["ErrWgElevationUnavailable"] = "ویندوز حاضر نشد به تونل رله از پوشه‌ای که در آن نصب شده دسترسی مدیر بدهد، برای همین اصلاً از شما نپرسید. معمولاً یعنی آن پوشه به درایو دیگری منتقل شده. نصب دوبارهٔ رله در مسیری که منتقل نشده باشد مشکل را حل می‌کند.",
        ["ErrWgNoHandshake"] = "تونل بالا آمد ولی گوشی پاسخی نداد. یا کد گوشی عوض شده — با هر بار شروع دوبارهٔ اشتراک عوض می‌شود — یا وی‌پی‌ان روی گوشی پاسخ‌های رله را می‌بلعد، که خود گوشی روی صفحه‌اش می‌گوید.",
        ["ErrTitlePairing"] = "گوشی نپذیرفت",
        ["ErrPairingDenied"] = "گوشی این کامپیوتر را رد کرد، یا کسی به پیام روی گوشی پاسخ نداد. روی گوشی «اجازه» را بزنید و دوباره کد را وارد کنید.",
        ["ErrPairingVersion"] = "این گوشی نسخهٔ قدیمی‌تری از رله دارد که اتصال با کد را پشتیبانی نمی‌کند. رله را روی گوشی به‌روزرسانی کنید، یا به‌جایش کد QR آن را اسکن کنید.",
        ["ErrWgStopFailed"] = "پروسهٔ تونل بسته نشد. رله را دوباره اجرا کنید؛ آداپتور و مسیرهایش با بسته شدن آن پاک می‌شوند.",
        ["ErrCameraDenied"] = "رله به دوربین دسترسی ندارد — ممکن است نبودن دوربین، اشغال توسط برنامه‌ای دیگر، یا مسدودبودن باشد. در تنظیمات ویندوز > حریم خصوصی دسترسی دوربین را فعال کنید، یا کد را دستی وارد کنید.",
    };
}
